/*
 * embed_vectors — generate embedded_vectors.c at build time.
 *
 * Walks a vectors directory, reads every .json file, and emits a C source
 * file containing them as string literals. This keeps lace-conformance
 * fully self-contained when built with EMBED_VECTORS=1 — no runtime
 * data directory needed.
 *
 * Usage: embed_vectors <vectors_root> <out.c>
 *
 * Output exposes:
 *   typedef struct { const char *rel; const char *json; size_t len; } embedded_vector_t;
 *   extern const embedded_vector_t EMBEDDED_VECTORS[];
 *   extern const size_t EMBEDDED_VECTOR_COUNT;
 */

#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
#endif
#ifndef _DEFAULT_SOURCE
#define _DEFAULT_SOURCE
#endif

#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

/* ── growable path list ───────────────────────────────────────────── */

typedef struct {
    char **paths;
    size_t n, cap;
} pathlist_t;

static void pathlist_add(pathlist_t *pl, const char *p) {
    if (pl->n >= pl->cap) {
        pl->cap = pl->cap ? pl->cap * 2 : 64;
        pl->paths = realloc(pl->paths, pl->cap * sizeof(char *));
        if (!pl->paths) { perror("realloc"); exit(1); }
    }
    pl->paths[pl->n++] = strdup(p);
}

static int pathcmp(const void *a, const void *b) {
    return strcmp(*(const char **)a, *(const char **)b);
}

/* ── recursive directory walk ─────────────────────────────────────── */

static void collect_json(const char *dir, const char *prefix, pathlist_t *out) {
    DIR *d = opendir(dir);
    if (!d) return;
    struct dirent *e;
    while ((e = readdir(d))) {
        if (e->d_name[0] == '.') continue;

        char full[4096], rel[4096];
        snprintf(full, sizeof(full), "%s/%s", dir, e->d_name);
        if (prefix[0])
            snprintf(rel, sizeof(rel), "%s/%s", prefix, e->d_name);
        else
            snprintf(rel, sizeof(rel), "%s", e->d_name);

        struct stat st;
        if (stat(full, &st) != 0) continue;
        if (S_ISDIR(st.st_mode)) {
            collect_json(full, rel, out);
        } else if (S_ISREG(st.st_mode)) {
            size_t nlen = strlen(e->d_name);
            if (nlen > 5 && strcmp(e->d_name + nlen - 5, ".json") == 0)
                pathlist_add(out, rel);
        }
    }
    closedir(d);
}

/* ── emit a C string literal for arbitrary bytes ──────────────────── */

static void emit_c_string(FILE *out, const unsigned char *data, size_t len) {
    fputc('"', out);
    for (size_t i = 0; i < len; i++) {
        unsigned char c = data[i];
        switch (c) {
        case '\\': fputs("\\\\", out); break;
        case '"':  fputs("\\\"", out); break;
        case '\n': fputs("\\n", out);  break;
        case '\r': fputs("\\r", out);  break;
        case '\t': fputs("\\t", out);  break;
        default:
            if (c >= 0x20 && c < 0x7f) {
                fputc(c, out);
            } else {
                /* Hex escape + empty string to terminate the escape so
                 * a following hex digit isn't consumed greedily. */
                fprintf(out, "\\x%02x\"\"", c);
            }
        }
    }
    fputc('"', out);
}

/* ── main ─────────────────────────────────────────────────────────── */

int main(int argc, char **argv) {
    if (argc != 3) {
        fprintf(stderr, "usage: embed_vectors <vectors_root> <out.c>\n");
        return 2;
    }
    const char *root = argv[1];
    const char *out_path = argv[2];

    struct stat rst;
    if (stat(root, &rst) != 0 || !S_ISDIR(rst.st_mode)) {
        fprintf(stderr, "error: %s is not a directory\n", root);
        return 2;
    }

    pathlist_t pl = {0};
    collect_json(root, "", &pl);
    qsort(pl.paths, pl.n, sizeof(char *), pathcmp);

    FILE *out = fopen(out_path, "w");
    if (!out) { perror(out_path); return 2; }

    fprintf(out, "/* Auto-generated by tools/embed_vectors — do not edit by hand. */\n");
    fprintf(out, "#include <stddef.h>\n\n");
    fprintf(out, "typedef struct { const char *rel; const char *json; size_t len; } embedded_vector_t;\n\n");
    fprintf(out, "/* %zu vectors embedded at build time. */\n", pl.n);
    fprintf(out, "const embedded_vector_t EMBEDDED_VECTORS[] = {\n");

    for (size_t i = 0; i < pl.n; i++) {
        char full[4096];
        snprintf(full, sizeof(full), "%s/%s", root, pl.paths[i]);

        FILE *f = fopen(full, "rb");
        if (!f) { fprintf(stderr, "warning: cannot read %s\n", full); continue; }
        fseek(f, 0, SEEK_END);
        long flen = ftell(f);
        fseek(f, 0, SEEK_SET);
        unsigned char *buf = malloc(flen > 0 ? (size_t)flen : 1);
        if (!buf) { fclose(f); continue; }
        size_t nread = fread(buf, 1, (size_t)flen, f);
        fclose(f);

        fprintf(out, "    { \"%s\",\n        ", pl.paths[i]);
        emit_c_string(out, buf, nread);
        fprintf(out, ", %zu },\n", nread);
        free(buf);
    }

    fprintf(out, "};\n\n");
    fprintf(out, "const size_t EMBEDDED_VECTOR_COUNT = %zu;\n", pl.n);
    fclose(out);

    fprintf(stderr, "wrote %s (%zu vectors)\n", out_path, pl.n);

    for (size_t i = 0; i < pl.n; i++) free(pl.paths[i]);
    free(pl.paths);
    return 0;
}
